FROM {{ item.basename }}

WORKDIR /app

COPY client .

RUN npm install npm@latest --global \
  && npm install \
  && npm install nodemon -g 
  #--save-dev

COPY server .
COPY docker-start.sh start.sh
COPY healthcheck.js healthcheck.js

RUN chmod +x start.sh

VOLUME /app/public/user-avatars
VOLUME /app/public/project-background-images
VOLUME /app/public/attachments

EXPOSE 1337

RUN apt-get update && apt-get install -y \
    openssh-server \
  && rm -rf /var/lib/apt/lists/* 

RUN mkdir ~/.ssh \
  && ssh-keygen -A \
  && echo "root:root" | chpasswd \
  && echo 'PasswordAuthentication no' >> /etc/ssh/sshd_config \
  && echo 'Port 22' >> /etc/ssh/sshd_config \
  && echo " \
Match User root \n\
  PubkeyAuthentication yes \n\
  AllowTcpForwarding yes\n\
  X11Forwarding yes\n\
  AllowAgentForwarding no\n\
" >> /etc/ssh/sshd_config

EXPOSE 22