FROM {{ item.basenamespace }}/{{ item.basename }}:{{ item.basetag }}

RUN apt-get update && apt-get install -y \
    openssh-server \
  && rm -rf /var/lib/apt/lists/* 

RUN mkdir ~/.ssh \
  && ssh-keygen -A \
  && echo "root:root" | chpasswd \
  && echo 'PasswordAuthentication no' >> /etc/ssh/sshd_config \
  && echo 'Port 22' >> /etc/ssh/sshd_config \
  && echo " \
Match User root \n\
  PubkeyAuthentication yes \n\
  AllowTcpForwarding yes\n\
  X11Forwarding yes\n\
  AllowAgentForwarding no\n\
" >> /etc/ssh/sshd_config

RUN sed -i 's/#ClientAliveInterval.*/ClientAliveInterval 60/g' /etc/ssh/sshd_config 

#I m not able to define alternative GOPATH for VSCode?!
#Decided to use tools downloaded by VSCode, so the dir gets overwritten by docker volume mount, still here for tests
RUN ln -s /go/ ~root/

EXPOSE 22