FROM {{ item.basenamespace }}/{{ item.basename }}:{{ item.basetag }} as builder

#COPY . /go/src/corteza-server
RUN ln -s /go/ ~root/
COPY . /go/src/corteza-server

WORKDIR /go/src/corteza-server
RUN make -C webapp/ all
RUN make build
RUN make release
#RUN git describe --tags --abbrev=0

# deploy stage
FROM ubuntu:20.04

RUN apt-get -y update \
 && apt-get -y install \
    ca-certificates \
    curl \
 && rm -rf /var/lib/apt/lists/*

ARG VERSION=2021.9.6
ARG SERVER_VERSION=${VERSION}
RUN mkdir -p /corteza/bin
COPY --from=builder /go/src/corteza-server/build/pkg/corteza-server /corteza
RUN mkdir -p /corteza/webapp/public
COPY --from=builder /go/src/corteza-server/webapp/public /corteza/webapp/public
#ARG CORTEZA_SERVER_PATH=https://releases.cortezaproject.org/files/corteza-server-${SERVER_VERSION}-linux-amd64.tar.gz
#RUN mkdir /tmp/server
#ADD $CORTEZA_SERVER_PATH /tmp/server

VOLUME /data

#RUN tar -zxvf "/tmp/server/$(basename $CORTEZA_SERVER_PATH)" -C / && \
#    rm -rf "/tmp/server" && \
#    mv /corteza-server /corteza

WORKDIR /corteza

HEALTHCHECK --interval=30s --start-period=1m --timeout=30s --retries=3 \
    CMD curl --silent --fail --fail-early http://127.0.0.1:80/healthcheck || exit 1

ENV STORAGE_PATH "/data"
ENV CORREDOR_ADDR "corredor:80"
ENV HTTP_ADDR "0.0.0.0:80"
ENV HTTP_WEBAPP_ENABLED "false"
ENV PATH "/corteza/bin:${PATH}"

EXPOSE 80

ENTRYPOINT ["./bin/corteza-server"]

CMD ["serve-api"]