FROM ubuntu:16.04 AS bbb-playback
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y language-pack-en \
    && update-locale LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8
RUN apt-get update \
    && apt-get install -y software-properties-common curl net-tools
RUN curl -sL https://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc | apt-key add - \
    && echo "deb http://ubuntu.bigbluebutton.org/xenial-220/ bigbluebutton-xenial main" >/etc/apt/sources.list.d/bigbluebutton.list
RUN useradd --system --user-group --home-dir /var/bigbluebutton bigbluebutton
RUN touch /.dockerenv
RUN apt-get update \
    && apt-get download bbb-playback-notes bbb-playback-podcast bbb-playback-presentation bbb-playback-screenshare \
    && dpkg -i --force-depends *.deb

FROM {{ item.namespace }}/{{ item.basename }}:{{ item.basetag }}

COPY --from=bbb-playback /etc/bigbluebutton/nginx /etc/bigbluebutton/nginx/
COPY --from=bbb-playback /var/bigbluebutton/playback /var/bigbluebutton/playback/
RUN sed -i '/location.*/a include snippets/auth.conf;' /etc/bigbluebutton/nginx/notes-playback.nginx \
    && sed -i '/location.*/a include snippets/auth.conf;' /etc/bigbluebutton/nginx/podcast.nginx \
    && sed -i '/location.*/a include snippets/auth.conf;' /etc/bigbluebutton/nginx/presentation.nginx \
    && sed -i '/location.*/a include snippets/auth.conf;' /etc/bigbluebutton/nginx/recording-screenshare.nginx
COPY ./nginx /etc/nginx/

ENV NGINX_HOSTNAME=localhost
#CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
CMD ["/etc/nginx/start"]