FROM {{ item.name }}:{{ item.tag }}

RUN apt-get update && apt-get install -y \
    systemd supervisor ocrmypdf tesseract-ocr-eng tesseract-ocr-deu \
  && rm -rf /var/lib/apt/lists/* \
  && mkdir /var/log/supervisord /var/run/supervisord \
  && mkdir -p /var/www/html/config \
  && chown -R www-data:root /var/www/html/config

# latest stable nextcloud LibreSign app needs 1.6.5
# Install Java and JsignPDF
RUN apt update
RUN mkdir -p /usr/share/man/man1
RUN apt-get install -y default-jre unzip
RUN curl -OL https://sourceforge.net/projects/jsignpdf/files/stable/JSignPdf%201.6.5/JSignPdf-1.6.5.zip \
    && unzip JSignPdf-1.6.5.zip -d /opt \
    && rm JSignPdf-1.6.5.zip

#RUN curl -OL https://sourceforge.net/projects/jsignpdf/files/stable/JSignPdf%202.0.0/jsignpdf-2.0.0.zip \
#    && unzip jsignpdf-2.0.0.zip -d /opt \
#    && rm jsignpdf-2.0.0.zip

# Apache selfsigned SSL -> only intern cause its behind nginx proxy
RUN a2enmod ssl
RUN mkdir /etc/apache2/ssl
RUN openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 \
    -subj "/C=DE/ST=SH/L=NA/O=intern/CN=next" \
    -keyout /etc/apache2/ssl/nextcloud.key -out /etc/apache2/ssl/nextcloud.crt

COPY nextcloud-ssl.conf /etc/apache2/sites-available/nextcloud-ssl.conf
RUN a2ensite nextcloud-ssl.conf
# Apache

#High performance push backend (only systemd nabled systems -> supervisored.conf)
#COPY notify_push.service /etc/systemd/system/notify_push.service
#COPY notify_push-watcher.service /etc/systemd/system/notify_push-watcher.service
#COPY notify_push-watcher.path /etc/systemd/system/notify_push-watcher.path
#RUN systemctl enable notify_push

# remove svg warning
RUN apt remove imagemagick
RUN sudo apt remove php-imagick
RUN apt install php-imagick imagemagick
#svg support
RUN apt install libmagickcore-dev 

COPY supervisord.conf /
ENV NEXTCLOUD_UPDATE=1 

CMD ["/usr/bin/supervisord", "-c", "/supervisord.conf"]